ame: prmerge-upload-crowdin
on:
  pull_request:
    types: [closed] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload strings.xml to Crowdin
      if: github.event.pull_request.merged == true
      env:
        CROWDIN_KEY: ${{ secrets.CROWDIN_TEST_API_KEY }}
      run: curl -F "files[Catroid/Strings/strings.xml]=@src/Catroid/Strings/strings.xml" -F "export_patterns[Catroid/Strings/strings.xml]=Catroid/Strings/strings.xml" https://api.crowdin.com/api/project/catrobatcrowdintestenvironment/update-file?key=$CROWDIN_KEY
